version: '3.8'

services:
  colorapp:
    restart: unless-stopped
    build: .
    container_name: colorapp
    ports:
      - 8000:8000
    volumes:
      - ./colorapp:/app
    env_file:
      - local.env
    depends_on:
      - db

  db:
    container_name: db
    restart: always
    image: postgres:15
    environment:
      POSTGRES_USER: color
      POSTGRES_PASSWORD: color
      POSTGRES_DB: color
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/colordb-data:/var/lib/postgresql/data
      - ./postgresql/colordb-logs:/var/log/postgresql


  color-migrate:
    build: .
    command: python manage.py migrate --noinput
    env_file:
      - local.env



