[tool.ruff]
line-length = 120
extend-ignore = ["F403", "UP030", "UP032"]
exclude = ["tests/"]
select = ["F", "W", "E", "C901", "I", "UP", "ASYNC", "S", "BLE", "FBT"]

[tool.ruff.lint.mccabe]
max-complexity = 11

[tool.ruff.lint.isort]
case-sensitive = true
combine-as-imports = true


[tool.black]
line-length = 120
target-version = ["py310"]
skip-string-normalization = true
exclude = '/(\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|\.svn|_build|buck-out|build|dist|migrations)/'


[tool.mypy]
python_version = 3.11
ignore_errors = false
implicit_reexport = true
explicit_package_bases = true
strict_equality = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true
warn_no_return = false
disallow_untyped_defs = true
warn_return_any = true
check_untyped_defs = true
plugins = ['pydantic.mypy']
ignore_missing_imports = true
plugins = ["mypy_django_plugin.main"]


[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
addopts = [
    "-v", "--exitfirst"
]
